export interface Input {
  criteria: number;
  button: number;
  type: number;
  amount: number;
}

export interface Game {
  name: string;
  critname: string[];
  critweight: number[];
  inputs: Input[];
}

const inputDefault: Input = {
  criteria: 0,
  button: 1,
  type: 0,
  amount: 1,
};

function fillPair(
  a: Input,
  afill: number,
  b: Input,
  bfill: number,
  n: number,
): Input[] {
  const array: Input[] = [];
  for (let i = 0; i < n * 2; i++) {
    if (i % 2 === 0) {
      array.push(...Array(afill).fill(a));
    } else {
      array.push(...Array(bfill).fill(b));
    }
  }
  return array;
}

export const gameData: Game[] = [
  { // Karate Man
    name: "Karate Man",
    critname: ["Single Punch", "Triple Punch"],
    critweight: [65, 25, 10],
    inputs: [
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Air Rally
    name: "Air Rally",
    critname: ["Normal Shot", "Long Shot"],
    critweight: [70, 20, 10],
    inputs: [
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        6,
        2,
      ),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Catchy Tune
    name: "Catchy Tune",
    critname: ["Orange", "Pineapple"],
    critweight: [40, 45, 15],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        4,
      ),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 2, button: 3 },
      { ...inputDefault, criteria: 2, button: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
    ],
  },
  { // Rhythm Tweezers
    name: "Rhythm Tweezers",
    critname: ["Short Hair"],
    critweight: [85, 15],
    inputs: [
      ...Array(39).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Figure Fighter
    name: "Figure Fighter",
    critname: ["Single Punch", "Double Punch"],
    critweight: [25, 60, 15],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        4,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // The Clappy Trio
    name: "The Clappy Trio",
    critname: ["Main", "Fast"],
    critweight: [50, 35, 15],
    inputs: [
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Shoot-'em-up
    name: "Shoot-'em-up",
    critname: ["Main", "Fast"],
    critweight: [45, 45, 10],
    inputs: [
      ...Array(17).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(20).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Micro-Row
    name: "Micro-Row",
    critname: ["Single March", "Triple March"],
    critweight: [45, 45, 10],
    inputs: [
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        3,
        3,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // First Contact
    name: "First Contact",
    critname: ["Main", "Pause", "Pork Rice Bowls"],
    critweight: [60, 15, 15, 10],
    inputs: [
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Bunny Hop
    name: "Bunny Hop",
    critname: ["Main", "Rest"],
    critweight: [70, 20, 10],
    inputs: [
      ...Array(37).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(20).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(23).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Exhibition Match
    name: "Exhibition Match",
    critname: ["Main", "Silent"],
    critweight: [60, 20, 20],
    inputs: [
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Sneaky Spirits
    name: "Sneaky Spirits",
    critname: ["Main", "Slow"],
    critweight: [50, 30, 20],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Rhythm Rally
    name: "Rhythm Rally",
    critname: ["Normal Swing", "Long Swing"],
    critweight: [70, 16, 14],
    inputs: [
      { ...inputDefault, criteria: 1 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Flipper-Flop
    name: "Flipper-Flop",
    critname: ["Flip", "Flipper-Roll"],
    critweight: [60, 30, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        15,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1, button: 2 },
        2,
        2,
      ),
    ],
  },
  { // Power Calligraphy
    name: "Power Calligraphy",
    critname: ["Main", "Chikara", "Kokoro", "Face"],
    critweight: [30, 25, 25, 10, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 4 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
    ],
  },
  { // Spaceball
    name: "Spaceball",
    critname: ["Normal Shot", "High Shot"],
    critweight: [55, 35, 10],
    inputs: [
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Dog Ninja
    name: "Dog Ninja",
    critname: ["Single Slice", "Double Slice"],
    critweight: [52, 40, 8],
    inputs: [
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        10,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
    ],
  },
  { // Hole in One
    name: "Hole in One",
    critname: ["Monkey", "Mandrill"],
    critweight: [60, 30, 10],
    inputs: [
      ...Array(17).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        1,
        3,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
    ],
  },
  { // Sumo Brothers
    name: "Sumo Brothers",
    critname: ["Slap", "Stomp", "Pose"],
    critweight: [35, 35, 20, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        8,
        { ...inputDefault, criteria: 0 },
        8,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
      { ...inputDefault, criteria: 3, button: 2 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
    ],
  },
  { // Lush Remix
    name: "Lush Remix",
    critname: ["Normal", "Keep the Beat"],
    critweight: [46, 44, 10],
    inputs: [
      ...Array(21).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(12).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Karate Man Returns!
    name: "Karate Man Returns!",
    critname: ["Single Punch", "Triple Punch"],
    critweight: [65, 25, 10],
    inputs: [
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        10,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Air Rally 2
    name: "Air Rally 2",
    critname: ["Normal Shot", "Far Shot", "Long Shot"],
    critweight: [44, 20, 30, 6],
    inputs: [
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        3,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 3 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      ...Array(8).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Catchy Tune 2
    name: "Catchy Tune 2",
    critname: ["Orange", "Pineapple"],
    critweight: [45, 40, 15],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        3,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 2, button: 3 },
      { ...inputDefault, criteria: 2, button: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
    ],
  },
  { // Figure Fighter 2
    name: "Figure Fighter 2",
    critname: ["Single Punch", "Triple Punch", "Double Punch"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        3,
        4,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
    ],
  },
  { // The Clappy Trio 2
    name: "The Clappy Trio 2",
    critname: ["Main", "Fast"],
    critweight: [50, 36, 14],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Shoot-'em-up 2
    name: "Shoot-'em-up 2",
    critname: ["Main", "Fast"],
    critweight: [50, 40, 10],
    inputs: [
      ...Array(35).fill({ ...inputDefault, criteria: 0 }),
      ...Array(8).fill({ ...inputDefault, criteria: 1 }),
      ...Array(23).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...Array(31).fill({ ...inputDefault, criteria: 1 }),
      ...Array(23).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Micro-Row 2
    name: "Micro-Row 2",
    critname: ["Single March", "Triple March"],
    critweight: [40, 46, 14],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        14,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        3,
        3,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        3,
        { ...inputDefault, criteria: 0 },
        2,
        3,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        4,
        { ...inputDefault, criteria: 1 },
        6,
        2,
      ),
    ],
  },
  { // Second Contact
    name: "Second Contact",
    critname: ["Main", "Pause", "Awkward"],
    critweight: [40, 10, 40, 10],
    inputs: [
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...Array(7).fill({ ...inputDefault, criteria: 2 }),
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...Array(11).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Citrus Remix
    name: "Citrus Remix",
    critname: ["Main", "Keep the Beat", "Repeat"],
    critweight: [25, 25, 40, 10],
    inputs: [
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        5,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        4,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 0 },
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
    ],
  },
  { // Working Dough
    name: "Working Dough",
    critname: ["Small Ball", "Big Ball"],
    critweight: [52, 40, 8],
    inputs: [
      ...Array(24).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1, button: 2 },
        2,
        2,
      ),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        7,
        2,
      ),
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(18).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 2 }),
      { ...inputDefault, criteria: 2 },
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
    ],
  },
  { // Sneaky Spirits 2
    name: "Sneaky Spirits 2",
    critname: ["Main", "Quiet", "Slow"],
    critweight: [32, 24, 24, 20],
    inputs: [
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Rhythm Rally 2
    name: "Rhythm Rally 2",
    critname: ["Normal Swing", "Fast Swing", "Long Swing"],
    critweight: [40, 32, 20, 8],
    inputs: [
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Flipper-Flop 2
    name: "Flipper-Flop 2",
    critname: ["Flip", "Triple Flip", "Flipper-Roll"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(7).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(8).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(9).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(10).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        3,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Tap Trial
    name: "Tap Trial",
    critname: ["Single Tap", "Double Tap", "Triple Tap", "Jump Tap"],
    critweight: [25, 25, 25, 17, 8],
    inputs: [
      { ...inputDefault, criteria: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        2,
        4,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 3 },
        2,
        3,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 4 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
    ],
  },
  { // Ringside
    name: "Ringside",
    critname: ["Speak", "Flex", "Pose"],
    critweight: [23, 29, 40, 8],
    inputs: [
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 2, button: 2 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 2, button: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2, button: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 2, button: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2, button: 2 },
      { ...inputDefault, criteria: 3, button: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 2, button: 2 }),
    ],
  },
  { // Ninja Bodyguard
    name: "Ninja Bodyguard",
    critname: ["Main"],
    critweight: [70, 30],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 0, button: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Freeze Frame
    name: "Freeze Frame",
    critname: ["Triple Car", "Double Car", "Fast Car"],
    critweight: [30, 20, 40, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 2 },
        2,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Launch Party
    name: "Launch Party",
    critname: ["Act 1", "Act 2"],
    critweight: [40, 52, 8],
    inputs: [
      ...Array(20).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(20).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // Marching Orders
    name: "Marching Orders",
    critname: ["March", "Halt", "Turn"],
    critweight: [40, 25, 25, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        11,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 2, button: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      { ...inputDefault, criteria: 2, button: 3 },
      ...Array(15).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 3 }),
      ...Array(18).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Munchy Monk
    name: "Munchy Monk",
    critname: ["Eat One", "Eat Two", "Eat Three"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        7,
        3,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        1,
        4,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 2 },
        3,
        3,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // See-Saw
    name: "See-Saw",
    critname: ["Main", "High Jump"],
    critweight: [40, 50, 10],
    inputs: [
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(8).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 1 },
      ...Array(20).fill({ ...inputDefault, criteria: 0 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Blue Bear
    name: "Blue Bear",
    critname: ["Donut", "Cake"],
    critweight: [35, 40, 25],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1, button: 3 },
        3,
        2,
      ),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 2, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 1, button: 3 },
    ],
  },
  { // Space Dance
    name: "Space Dance",
    critname: ["Pose", "Squat", "Punch"],
    critweight: [45, 25, 25, 10],
    inputs: [
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 3 },
        5,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0, button: 3 }),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 1, button: 3 }),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0, button: 3 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Lockstep
    name: "Lockstep",
    critname: ["Onbeat", "Offbeat", "Switch"],
    critweight: [20, 34, 40, 6],
    inputs: [
      ...Array(15).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        3,
        { ...inputDefault, criteria: 2 },
        6,
        3,
      ),
      ...Array(7).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 3 },
      { ...inputDefault, criteria: 2 },
      ...Array(15).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(30).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // The Snappy Trio
    name: "The Snappy Trio",
    critname: ["Main", "Offbeat"],
    critweight: [70, 10, 20],
    inputs: [
      ...Array(21).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Figure Fighter 3
    name: "Figure Fighter 3",
    critname: ["Single Punch", "Triple Punch", "Double Punch"],
    critweight: [18, 35, 37, 10],
    inputs: [
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 0 },
        4,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        10,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
    ],
  },
  { // Tap Trial 2
    name: "Tap Trial 2",
    critname: ["Single Tap", "Double Tap", "Triple Tap", "Jump Tap"],
    critweight: [37, 10, 28, 15, 10],
    inputs: [
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 3 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 4 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 3 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
    ],
  },
  { // Hole in One 2
    name: "Hole in One 2",
    critname: ["Monkey", "Mandrill"],
    critweight: [50, 40, 10],
    inputs: [
      { ...inputDefault, criteria: 1 },
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        3,
        3,
      ),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        7,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        7,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // Cosmic Dance
    name: "Cosmic Dance",
    critname: ["Pose", "Squat", "Punch"],
    critweight: [45, 30, 15, 10],
    inputs: [
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 3 },
        3,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0, button: 3 }),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 3 },
      { ...inputDefault, criteria: 0, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        2,
        { ...inputDefault, criteria: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Cosmic Rhythm Rally
    name: "Cosmic Rhythm Rally",
    critname: ["Normal Swing", "Fast Swing", "Long Swing"],
    critweight: [40, 36, 14, 10],
    inputs: [
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Working Dough 2
    name: "Working Dough 2",
    critname: ["Small Ball", "Big Ball"],
    critweight: [45, 40, 15],
    inputs: [
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        4,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 2 }),
      { ...inputDefault, criteria: 2 },
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
    ],
  },
  { // Double Date
    name: "Double Date",
    critname: ["Soccer Ball", "Basketball", "Rugby Ball"],
    critweight: [40, 30, 22, 8],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Catch of the Day
    name: "Catch of the Day",
    critname: ["Quicknibble", "Pausegill", "Threefish"],
    critweight: [45, 20, 20, 15],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 2 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 3 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Fork Lifter
    name: "Fork Lifter",
    critname: ["Main", "Fast"],
    critweight: [40, 45, 15],
    inputs: [
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        5,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Love Rap
    name: "Love Rap",
    critname: ["Main", "All about you!", "Fo' sho'!"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Bossa Nova
    name: "Bossa Nova",
    critname: ["Left Side", "Right Side"],
    critweight: [35, 55, 10],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        3,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        4,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...Array(13).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(7).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        5,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Board Meeting
    name: "Board Meeting",
    critname: ["Single", "All"],
    critweight: [56, 30, 14],
    inputs: [
      { ...inputDefault, criteria: 1 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Packing Pests
    name: "Packing Pests",
    critname: ["Main", "Double Up"],
    critweight: [35, 55, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        3,
      ),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 2, button: 2 },
    ],
  },
  { // Monkey Watch
    name: "Monkey Watch",
    critname: ["High-five", "Ooki oo!"],
    critweight: [50, 40, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        7,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        2,
        7,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        7,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
];
/*
{ ...inputDefault, criteria: 0 },

...Array(2).fill({ ...inputDefault, criteria: 0 }),

...fillPair({ ...inputDefault, criteria: 0 },1,
                  { ...inputDefault, criteria: 0 },1,
        2),

{ //
    name: "",
    critname: ["",""],
    critweight: [,,],
    inputs: [

    ],
  },
*/
